### ISSUE TITLE
new to this

### ISSUE THREAD

**Issue by gorobei9** [danktagma/meta#1]
git clone ... seems fine.

so I edit the syllabus, then try to push:

bash-3.2$ git push
remote: Permission to danktagma/meta.git denied to gorobei9.
fatal: unable to access 'https://github.com/danktagma/meta/': The requested URL returned error: 403

**Comment by beeblebroxz** [comment]
Fixing.

**Comment by beeblebroxz** [comment]
I've changed default permissions for all members. Everyone should have admin access now. @gorobei9 - can you try the push again?
